# Generated by Django 6.0.5 on 2026-06-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField()),
                ('banner_image', models.URLField(blank=True)),
            ],
        ),
    ]
